# Generated by Django 3.2.12 on 2022-03-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_address',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='processed_amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='requested_amount',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='processedtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.AddConstraint(
            model_name='destinationaddress',
            constraint=models.UniqueConstraint(fields=('deposit_address', 'destination_address'), name='unique_deposit_des_address'),
        ),
    ]
