# Generated by Django 3.2.12 on 2022-03-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0002_auto_20220314_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='requested_amount',
        ),
        migrations.AddField(
            model_name='deposit',
            name='after_fee_amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposited_amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16, null=True),
        ),
    ]
