# Generated by Django 3.2.12 on 2022-03-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0004_deposit_no_of_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='transfer_complete',
            field=models.BooleanField(default=False),
        ),
    ]
